services:
  db:
    image: mariadb:10.11
    container_name: recipe-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - recipe-network
    deploy:
      resources:
        limits:
          memory: 512M # O MariaDB com 512MB
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3

  # --- SERVIÇO DO BACKEND (Laravel) ---
  app:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    container_name: recipe-backend
    restart: unless-stopped
    working_dir: /var/www
    dns:
      - 8.8.8.8
    volumes:
      - ./laravel:/var/www
    networks:
      - recipe-network
    depends_on:
      db:
        condition: service_healthy # Só inicia o Laravel quando o banco estiver pronto
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          memory: 128M

  # --- SERVIDOR WEB (Nginx) ---
  nginx:
    image: nginx:alpine
    container_name: recipe-webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./laravel:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - recipe-network
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 128M

  # --- SERVIÇO DO FRONTEND (Next.js) ---
  next:
    build:
      context: ./next
      dockerfile: Dockerfile
    container_name: recipe-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./next:/app
      - next_node_modules:/app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
      - WATCHPACK_POLLING=true
    networks:
      - recipe-network
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
        reservations:
          memory: 512M

networks:
  recipe-network:
    driver: bridge

volumes:
  next_node_modules:
  mariadb_data: # Volume persistente
